# Generated by Django 5.0.2 on 2024-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('category_offer_description', models.TextField(blank=True, null=True)),
                ('category_offer', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
