# Generated by Django 5.0.2 on 2024-03-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Out of delivery', 'Out of delivery'), ('Return', 'Return'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
