# Generated by Django 5.0.2 on 2024-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash on delivery", "Cash on delivery"),
                    ("Razor Pay", "Razor Pay"),
                    ("walletbalance", "Wallet Balance"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
