# Generated by Django 5.0.2 on 2024-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0011_order_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
