# Generated by Django 5.0.4 on 2024-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0016_userwishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon_discount_amount",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
