# Generated by Django 5.0.4 on 2024-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0017_cart_coupon_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash on delivery", "Cash on delivery"),
                    ("walletbalance", "Wallet Balance"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
