# Generated by Django 5.0.4 on 2024-04-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_products_actual_price"),
        ("user_profile", "0018_alter_payment_payment_type_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
            ),
        ),
    ]
