# Generated by Django 5.0.2 on 2024-02-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='image',
        ),
        migrations.AddField(
            model_name='product_images',
            name='product_images',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
