# Generated by Django 5.0.2 on 2024-02-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_images_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_images',
            old_name='product_images',
            new_name='product_image',
        ),
    ]
