# Generated by Django 5.0.2 on 2024-02-26 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_images_product_images_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_images',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='product_images',
            name='product_image2',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_images',
            name='product_image3',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_images',
            name='product_image4',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_images',
            name='product_image5',
            field=models.ImageField(default=datetime.datetime(2024, 2, 26, 10, 16, 15, 206133, tzinfo=datetime.timezone.utc), upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
