# Generated by Django 5.0.4 on 2024-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_products_actual_price_alter_products_offer_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="actual_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
